name: musica_client
description: Camada Flutter/GetConnect para a API REST de músicas.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
